AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  postImages:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: postImages/
      Handler: post-images.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::****:role/lambda-dynamodb-access
      Environment:
        Variables:
          BUCKET_NAME: your-photos-bucket
          TABLE_NAME: photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images
            Method: post
  updateImage:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      CodeUri: updateImage/
      Handler: update-image.lambda_handler
      Runtime: python3.6
      MemorySize: 128
      Timeout: 15
      Role: arn:aws:iam::::****::role/lambda-dynamodb-access
      Environment:
        Variables:
          BUCKET_NAME: your-photos-bucket
          TABLE_NAME: photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images
            Method: PUT
  getImages:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      CodeUri: getImages/
      Handler: get-image.lambda_handler
      Runtime: python3.6
      MemorySize: 128
      Timeout: 3
      Role: arn:aws:iam::::****::role/lambda-dynamodb-access
      Environment:
        Variables:
          BUCKET_NAME: your-photos-bucket
          TABLE_NAME: photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images
            Method: get
  getImageById:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      CodeUri: getImageById/
      Handler: get-image-by-id.lambda_handler
      Runtime: python3.6
      MemorySize: 128
      Timeout: 3
      Role: arn:aws:iam::::****::role/lambda-dynamodb-access
      Environment:
        Variables:
          BUCKET_NAME: your-photos-bucket
          TABLE_NAME: photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images/{id}
            Method: get
  deleteImageById:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      CodeUri: deleteImageById/
      Handler: delete-image-by-id.lambda_handler
      Runtime: python3.6
      MemorySize: 128
      Timeout: 3
      Role: arn:aws:iam::::****::role/lambda-dynamodb-access
      Environment:
        Variables:
          BUCKET_NAME: your-photos-bucket
          TABLE_NAME: photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images/{id}
            Method: delete